# NLP Assignment 4
## Submitted by Chaitanya Jindal

### Problem Statement

Dataset: Demonetization_tweets.csv

Tasks:
1. Find the Top 50 Mentions (@)
2. Find the Top 50 Hashtags (#)
3. Find Tweets Mentioning the Prime Minister
4. Use Prepositions to Extract Relevant Information from Tweets

### Importing Libraries

In [1]:
import nltk
import re

import pandas as pd

from collections import Counter

### Loading Dataset

In [6]:
df = pd.read_csv("demonetization_tweets.csv", encoding='latin-1')

print("Number of Tweets:", len(df))
df.head()

Number of Tweets: 14940

,Unnamed: 0,X,text,favorited,favoriteCount,replyToSN,created,truncated,replyToSID,id,replyToUID,statusSource,screenName,retweetCount,isRetweet,retweeted
0,1,1,RT @rssurjewala: Critical question: Was PayTM ...,False,0,NaN,2016-11-23 18:40:30,False,NaN,8.014957e+17,NaN,"<a href=""http://twitter.com/download/android"" ...",HASHTAGFARZIWAL,331,True,False
1,2,2,RT @Hemant_80: Did you vote on #Demonetization...,False,0,NaN,2016-11-23 18:40:29,False,NaN,8.014957e+17,NaN,"<a href=""http://twitter.com/download/android"" ...",PRAMODKAUSHIK9,66,True,False
2,3,3,"RT @roshankar: Former FinSec, RBI Dy Governor,...",False,0,NaN,2016-11-23 18:40:03,False,NaN,8.014955e+17,NaN,"<a href=""http://twitter.com/download/android"" ...",rahulja13034944,12,True,False
3,4,4,RT @ANI_news: Gurugram (Haryana): Post office ...,False,0,NaN,2016-11-23 18:39:59,False,NaN,8.014955e+17,NaN,"<a href=""http://twitter.com/download/android"" ...",deeptiyvd,338,True,False
4,5,5,RT @satishacharya: Reddy Wedding! @mail_today ...,False,0,NaN,2016-11-23 18:39:39,False,NaN,8.014954e+17,NaN,"<a href=""http://cpimharyana.com"" rel=""nofollow...",CPIMBadli,120,True,False

### Identifying the Tweet Text Column

In [7]:
print(df.columns)

Index(['Unnamed: 0', 'X', 'text', 'favorited', 'favoriteCount', 'replyToSN',
       'created', 'truncated', 'replyToSID', 'id', 'replyToUID',
       'statusSource', 'screenName', 'retweetCount', 'isRetweet', 'retweeted'],
      dtype='str')

In [8]:
tweets = df['text'].astype(str)

### Task 1: Top 50 Mentions (@)

In [9]:
mentions = []

for tweet in tweets:
    mentions.extend(re.findall(r'@\w+', tweet))

top_mentions = Counter(mentions).most_common(50)

top_mentions_df = pd.DataFrame(top_mentions,
                               columns=['Mention','Frequency'])

top_mentions_df

             Mention  Frequency
0       @evanspiegel       1311
1   @URautelaForever       1273
2      @narendramodi       1138
3     @gauravcsawant        541
4       @ModiBharosa        540
5    @DrKumarVishwas        358
6           @5Forty3        286
7       @rssurjewala        284
8      @rahulroushan        284
9          @PMOIndia        246
10    @centerofright        237
11    @ShashiTharoor        231
12   @DasShaktikanta        195
13   @ArvindKejriwal        185
14      @steve_hanke        179
15        @ashu3page        171
16          @YouTube        159
17        @kanimozhi        153
18      @RoflGandhi_        151
19        @AskAnshul        149
20          @Timcast        147
21  @Atheist_Krishna        135
22          @ippatel        116
23           @Joydas        114
24      @arunjaitley        114
25         @jamewils        114
26        @PIB_India        113
27      @FinMinIndia        104
28    @attomeybharti        103
29      @Joydeep_911        102
30        @Memeghnad         95
31  @PiyushGoyalOffc         95
32       @DrGPradhan         90
33              @dna         85
34   @arvindsubraman         80
35  @priyaakulkarni2         80
36       @minimathur         79
37        @MIB_India         79
38         @Ra_THORe         75
39          @pGurus1         74
40     @_MiteshPatel         73
41         @aartic02         72
42     @aaanupriyaaa         70
43       @NG_withINC         68
44        @Hemant_80         62
45          @jairajp         62
46     @harshkkapoor         60
47               @na         59
48    @ShirishKunder         56
49       @anandkamal         54

### Task 2: Top 50 Hashtags (#)

In [10]:
hashtags = []

for tweet in tweets:
    hashtags.extend(re.findall(r'#\w+', tweet))

top_hashtags = Counter(hashtags).most_common(50)

top_hashtags_df = pd.DataFrame(top_hashtags,
                               columns=['Hashtag','Frequency'])

top_hashtags_df

                   Hashtag  Frequency
0          #Demonetization       3884
1          #demonetization       3783
2          #DeMonetization        920
3                   #India        356
4             #nitishkumar        257
5                    #demo        174
6                   #GLvMI        145
7     #CorruptionFreeIndia        103
8              #BlackMoney         96
9                    #Modi         92
10            #VijayMallya         86
11  #IndiaFightsCorruption         79
12         #DEMONETIZATION         60
13                    #BJP         56
14            #NoMoneyYaar         53
15            #Demonetizat         47
16              #SonuNigam         47
17         #DeMonetisation         45
18              #RatanTata         44
19               #Insights         44
20               #bulletin         44
21        #boycottsnapchat         44
22                    #RBI         42
23           #NarendraModi         41
24          #LifeInsurance         34
25         #demonetisation         31
26          #YouTubeIsDead         30
27                  #NMApp         29
28      #MeraDeshBadalRaha         28
29                 #PMModi         26
30                   #news         25
31               #TrustBJP         25
32                #Bypolls         24
33                    #not         23
34                #YouTube         23
35               #CGDTalks         23
36             #IndiaKaDil         22
37                  #india         22
38              #Hilarious         21
39             #blackmoney         20
40                 #Hitler         20
41              #WarOnCash         20
42              #lifehacks         19
43               #Doltiwal         18
44       #JaiChandKejriwal         18
45                 #survey         18
46                     #PM         18
47                  #Delhi         18
48              #NorthEast         18
49                #ITVideo         18

### Task 3: Tweets Mentioning Prime Minister

In [11]:
pm_tweets = tweets[
    tweets.str.contains(
        r'Prime Minister|PM|Modi|Narendra Modi',
        case=False,
        na=False
    )
]

print("Number of Tweets Found:", len(pm_tweets))

Number of Tweets Found: 5187

### Display First 20 Tweets Mentioning Prime Minister

In [12]:
for i, tweet in enumerate(pm_tweets.head(20), start=1):
    print(f"\nTweet {i}:")
    print(tweet)

Tweet 1:
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;


Tweet 2:
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?

Tweet 3:
RT @sumitbhati2002: Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support oppositio


Tweet 4:
Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support opposition just b'coz of party

Tweet 5:
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r

Tweet 6:
RT @Dipankar_cpiml: The Modi app on #DeMonetization proves once again that the govt is totally indifferent to the mounting misery and hards


Tweet 7:
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?

Tweet 8:
RT @MahikaInfra: @narendramodi
@Swamy39
The success of #Demonetization will depend on how swiftly govt replenish the currency

Pls avoid Ba


Tweet 9:
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?

Tweet 10:
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?

Tweet 11:
RT @Gadgets360: After the #demonetization, searches about #NarendraModi's app are trending on app stores https://t.co/ZetKRqqClX

Tweet 12:
@arunjaitley @narendramodi Lrnd frm a frnd-Banks r asking employees to comeback 2sales &amp; BAU Operations #Demonetization

Tweet 13:
RT @kanimozhi: Ts is exactly what Pappu &amp; opposition has done to themselves by opposing #Demonetization Now none can stop Modi bandwagon ti


Tweet 14:
RT @rohanmlw: #demonetization eye opener video bt i doubt as few jurnos don't want2 hear +ve of @narendramodi @sardesairajdeep @ravishndtv


Tweet 15:
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha


Tweet 16:
RT @nmleo1: Is #ModiSarkar 's #achedin campaign on #demonetization a #goebbelsian #masterstroke that turns blind eye to #GroundZero shocks?


Tweet 17:
RT @Punitspeaks: Survey result so far by @PMOIndia on #Demonetization. 5 lakh response in 24 hrs. 90% supports note ban. #MeraDeshBadalRaha


Tweet 18:
RT @pGurus1: #Demonetization The time has come to put MUDRA into action, writes Prof. R Vaidyanathan - https://t.co/P6HkkDVa3b @upma23 @UnS


Tweet 19:
RT @pGurus1: #Demonetization move of Modi; Who is supporting it, who is opposing it and why? A complete coverage of all parties - https://t


Tweet 20:
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r

### Task 4: Extracting Prepositions from Tweets

In [13]:
prepositions = []

for tweet in tweets:
    
    tokens = nltk.word_tokenize(tweet)
    pos_tags = nltk.pos_tag(tokens)
    
    for word, tag in pos_tags:
        if tag == 'IN':
            prepositions.append(word.lower())

preposition_freq = Counter(prepositions)

pd.DataFrame(
    preposition_freq.most_common(50),
    columns=['Preposition','Frequency']
)

        Preposition  Frequency
0                in       4708
1                of       4104
2                on       2812
3              that       1970
4               for       1732
5                by       1515
6             after       1338
7              from       1333
8       evanspiegel       1285
9              with        811
10               if        615
11          against        614
12            since        596
13               at        578
14             over        557
15           across        453
16               as        441
17             like        405
18            about        384
19          whether        341
20             than        222
21              via        202
22           during        188
23           before        185
24          through        134
25              out        120
26            among        115
27             into        102
28            worth         93
29          because         76
30            along         76
31          despite         73
32            while         69
33              per         44
34           around         43
35  boycottsnapchat         43
36            under         39
37           though         33
38     narendramodi         33
39          without         29
40               so         25
41           behind         15
42             upon         12
43          between         12
44           beyond         12
45           unless         10
46             near          9
47  beingsalmankhan          9
48              off          9
49                |          8

### Sample Tweets with Prepositions

In [14]:
for tweet in tweets.head(20):
    
    tokens = nltk.word_tokenize(tweet)
    pos_tags = nltk.pos_tag(tokens)
    
    extracted = [word for word, tag in pos_tags if tag == 'IN']
    
    if extracted:
        print("\nTweet:")
        print(tweet)
        print("Prepositions:", extracted)

Tweet:
RT @rssurjewala: Critical question: Was PayTM informed about #Demonetization edict by PM? It's clearly fishy and requires full disclosure &amp;

Prepositions: ['by']

Tweet:
RT @Hemant_80: Did you vote on #Demonetization on Modi survey app?
Prepositions: ['on', 'on']

Tweet:
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th

Prepositions: ['If', 'for']

Tweet:
RT @ANI_news: Gurugram (Haryana): Post office employees provide cash exchange to patients in hospitals #demonetization https://t.co/uGMxUP9

Prepositions: ['in']

Tweet:
@DerekScissors1: Indias #demonetization: #Blackmoney a symptom, not the disease https://t.co/HSl6Ihj0Qe via @ambazaarmag
Prepositions: ['via']

Tweet:
RT @gauravcsawant: Rs 40 lakh looted from a bank in Kishtwar in J&amp;K. Third such incident since #demonetization. That's how terrorists have

Prepositions: ['from', 'in', 'in', 'since']

Tweet:
RT @Joydeep_911: Calling all Nationalists to join...
Walk for #CorruptionFreeIndia and spread the benefits of #Demonetization among the mas

Prepositions: ['for', 'of', 'among']

Tweet:
RT @sumitbhati2002: Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support oppositio

Prepositions: ['with', 'on']

Tweet:
National reform now destroyed even the essence of sagan. Such instances urge giving #demonetization a second though
 https://t.co/eyySIREiUq
Prepositions: ['of', 'though']

Tweet:
Many opposition leaders are with @narendramodi on the #Demonetization
And respect their decision,but support opposition just b'coz of party
Prepositions: ['with', 'on', 'of']

Tweet:
RT @Joydas: Question in Narendra Modi App where PM is taking feedback if people support his #DeMonetization strategy https://t.co/pYgK8Rmg7r
Prepositions: ['in', 'if']

Tweet:
@Jaggesh2 Bharat band on 28??<ed><U+00A0><U+00BD><ed><U+00B8><U+0082>Those who  are protesting #demonetization  are all different party leaders.
Prepositions: ['on']

Tweet:
RT @Atheist_Krishna: The effect of #Demonetization !!
. https://t.co/A8of7zh2f5
Prepositions: ['of']

Tweet:
RT @sona2905: When I explained #Demonetization to myself and tried to put it down in my words which are not laced with any heavy technical

Prepositions: ['in', 'with']

Tweet:
RT @Dipankar_cpiml: The Modi app on #DeMonetization proves once again that the govt is totally indifferent to the mounting misery and hards

Prepositions: ['on', 'that']

Tweet:
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th

Prepositions: ['If', 'for']

Tweet:
RT @Atheist_Krishna: BEFORE and AFTER Gandhi ji heard they are standing there against #Demonetization
. https://t.co/9NheK63TPg
Prepositions: ['against']

Tweet:
RT @pGurus1: #Demonetization The co-operative banking sector in Kerala is as good as a tax haven. Is Kerala a Black Money HQ? https://t.co/

Prepositions: ['in', 'as']

Tweet:
RT @roshankar: Former FinSec, RBI Dy Governor, CBDT Chair + Harvard Professor lambaste #Demonetization.

If not for Aam Aadmi, listen to th

Prepositions: ['If', 'for']

### Conclusion

In [15]:
print("Top 50 Mentions extracted successfully.")
print("Top 50 Hashtags extracted successfully.")
print("Tweets mentioning Prime Minister identified.")
print("Prepositions extracted using NLTK POS Tagging.")

Top 50 Mentions extracted successfully.
Top 50 Hashtags extracted successfully.
Tweets mentioning Prime Minister identified.
Prepositions extracted using NLTK POS Tagging.