# Assignment 1  
## Submitted by Chaitanya Jindal

#### Q1. Create a dataframe with the given dataset.

d = {
'player": ["M S Dhoni", "hardhik", "rahul", "Mohit sharma", "Andrerussel", "jashprret", "virat kohli", "rohit sharma"],
"Team": ["Chennai Super King", "Mumbai indians", "kings eleven", "GT", "kolkata knight riders", "Mumbai indians", "RCB", "Mumbai indians"],
"category": ["Batsman", "Batsman", "Batsman", "Bowler", "Bowler", "Batsman", "Batsman", "Batsman"],
"Bidprice": [13,11,10,12,7,10,17,15],
"Runs": [4000,2400,3000,1000,1500,3500,5000,3900]
}

In [6]:
import numpy as np
import pandas as pd

d={
    "Player": ["M S Dhoni", "Hardik", "Rahul", "Mohit Sharma", "Andre Russel", "Jaspreet", "Virat Kohli", "Rohit Sharma"],
    "Team": ["Chennai Super Kings", "Mumbai Indians", "Kings Eleven Punjab", "Gujrat Titans", "Kolkata Knight Riders", "Mumbai Indians", "Royal Challengers Bangalore", "Mumbai Indians"],
    "Category":["Batsman", "Batsman", "Batsman", "Bowler", "Bowler", "Batsman", "Batsman", "Batsman"],
    "Bidprice":[13, 11, 10, 12, 7, 10, 17, 15],
    "Runs":[4000, 2400, 3000, 1000, 1500, 3500, 5000, 3900]
    }

df = pd.DataFrame(d)
print(df)

         Player                         Team Category  Bidprice  Runs
0     M S Dhoni          Chennai Super Kings  Batsman        13  4000
1        Hardik               Mumbai Indians  Batsman        11  2400
2         Rahul          Kings Eleven Punjab  Batsman        10  3000
3  Mohit Sharma                Gujrat Titans   Bowler        12  1000
4  Andre Russel        Kolkata Knight Riders   Bowler         7  1500
5      Jaspreet               Mumbai Indians  Batsman        10  3500
6   Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000
7  Rohit Sharma               Mumbai Indians  Batsman        15  3900

#### Q2. Display all players who are categorized as Bowlers.

In [17]:
df[df['Category'] == 'Bowler'][['Player', 'Category']]

         Player Category
3  Mohit Sharma   Bowler
4  Andre Russel   Bowler

#### Q3. Display all players who belong to the Mumbai Indians team.

In [18]:
df[df["Team"] == 'Mumbai Indians'][['Player', 'Team']]

         Player            Team
1        Hardik  Mumbai Indians
5      Jaspreet  Mumbai Indians
7  Rohit Sharma  Mumbai Indians

#### Q4. Display all Mumbai Indians players whose total runs are greater than 3000.

In [30]:
df[(df["Team"] == 'Mumbai Indians') & (df["Runs"] >= 3000)][['Player', 'Team', 'Runs']]

         Player            Team  Runs
5      Jaspreet  Mumbai Indians  3500
7  Rohit Sharma  Mumbai Indians  3900

#### Q5. Display the complete details of players who play for either RCB or Chennai Super King.

In [31]:
df[(df['Team'] == 'Chennai Super Kings') | (df['Team'] == 'Royal Challengers Bangalore')]

        Player                         Team Category  Bidprice  Runs
0    M S Dhoni          Chennai Super Kings  Batsman        13  4000
6  Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000

#### Q6. Calculate and print the average Bid Price and the average Runs of all players in the dataset.

In [42]:
print(f"Average Bid Price: {df["Bidprice"].mean()}\nAvergae Runs: {df["Runs"].mean()}")

Average Bid Price: 11.875
Avergae Runs: 3037.5

#### Q7. Sort the entire DataFrame based on the Bid Price in ascending and descending order.

In [48]:
print(f"Ascending DataFrame:\n{df.sort_values(by="Bidprice", ascending=True)}")
print(f"Descending DataFrame:\n{df.sort_values(by="Bidprice", ascending=False)}")

Ascending DataFrame:
         Player                         Team Category  Bidprice  Runs
4  Andre Russel        Kolkata Knight Riders   Bowler         7  1500
2         Rahul          Kings Eleven Punjab  Batsman        10  3000
5      Jaspreet               Mumbai Indians  Batsman        10  3500
1        Hardik               Mumbai Indians  Batsman        11  2400
3  Mohit Sharma                Gujrat Titans   Bowler        12  1000
0     M S Dhoni          Chennai Super Kings  Batsman        13  4000
7  Rohit Sharma               Mumbai Indians  Batsman        15  3900
6   Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000
Descending DataFrame:
         Player                         Team Category  Bidprice  Runs
6   Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000
7  Rohit Sharma               Mumbai Indians  Batsman        15  3900
0     M S Dhoni          Chennai Super Kings  Batsman        13  4000
3  Mohit Sharma                Gujrat Titans   Bowler        12  1000
1        Hardik               Mumbai Indians  Batsman        11  2400
2         Rahul          Kings Eleven Punjab  Batsman        10  3000
5      Jaspreet               Mumbai Indians  Batsman        10  3500
4  Andre Russel        Kolkata Knight Riders   Bowler         7  1500

#### Q8. Identify and display the most expensive player (player with the highest Bid Price).

In [60]:
df[df["Bidprice"] == df['Bidprice'].max()]

        Player                         Team Category  Bidprice  Runs
6  Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000

#### Q9. Identify and display the player with the lowest number of runs.

In [61]:
df[df["Runs"] == df["Runs"].min()]

         Player           Team Category  Bidprice  Runs
3  Mohit Sharma  Gujrat Titans   Bowler        12  1000

#### Q10. Print the total number of players (i.e., total number of rows) present in the dataset.

In [63]:
print(f"Total number of players: {df['Player'].count()}")

Total number of players: 8

#### Q11. Display the total number of players in each team using appropriate grouping techniques.

In [65]:
df.groupby("Team").size()

Team
Chennai Super Kings            1
Gujrat Titans                  1
Kings Eleven Punjab            1
Kolkata Knight Riders          1
Mumbai Indians                 3
Royal Challengers Bangalore    1
dtype: int64

#### Q12. Find and display the player who had the highest Bid Price from each team.

In [74]:
df.loc[df.groupby("Team")["Bidprice"].idxmax()]

         Player                         Team Category  Bidprice  Runs
0     M S Dhoni          Chennai Super Kings  Batsman        13  4000
3  Mohit Sharma                Gujrat Titans   Bowler        12  1000
2         Rahul          Kings Eleven Punjab  Batsman        10  3000
4  Andre Russel        Kolkata Knight Riders   Bowler         7  1500
7  Rohit Sharma               Mumbai Indians  Batsman        15  3900
6   Virat Kohli  Royal Challengers Bangalore  Batsman        17  5000

#### Q13. Calculate and display the average number of runs scored by players in each team.

In [77]:
df.groupby("Team")["Runs"].mean()

Team
Chennai Super Kings            4000.000000
Gujrat Titans                  1000.000000
Kings Eleven Punjab            3000.000000
Kolkata Knight Riders          1500.000000
Mumbai Indians                 3266.666667
Royal Challengers Bangalore    5000.000000
Name: Runs, dtype: float64